version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: momo
      POSTGRES_PASSWORD: 397zR3GGC
    deploy:
      replicas: 1
    volumes:
      - postgres-momo:/var/lib/postgresql/data
    networks:
      - external_network
    ports:
      - "5454:5432"  # Map container port 5432 to host port 5433 for ingress
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile for the Golang app
    image: momo:latest  # Use the desired image name and tag
    deploy:
      replicas: 1
    ports:
      - "8980:8980"  # Map container port 8980 to host port 8980
    networks:
      - external_network
    depends_on:
      - db  # Ensure that

volumes:
  postgres-momo:
  momo-public:

networks:
  external_network:
    external: true
  internal_network:
    internal: true
